### ISSUE TITLE
add second booster to "Cologne Vaccination Rates and Booster Rates"

### ISSUE THREAD

**Issue by jakobrehmann** [matsim-vsp/covid-sim#40]
vaccinationDetailed.tsv

1 = vaccinated
2 = booster
3 = 2nd booster

**Comment by jakobrehmann** [comment]
Context: "Cologne Vaccination Rates and Booster Rates" plot on covid-sim needs to be expanded to include more boosters. 

Current Behavior: the plot is created using data from infections.txt.csv. This isn't ideal because each time another round of boosters is instituted, we need a new column in that output (instead of just having columns "nVaccinated" and "nReVaccinated", we will also need "nReReVaccinated", "nReReReVaccinated", etc.) 

Desired Behavior: Base the plot on the output vaccinationDetailed.tsv. Each row contains the number of vaccinations given for each vaccination type and vaccination round (see key above). Thus, if some people got boostered with mNRA and boostered with vector on the same day, those doses would have to be aggregated for the plot. 

Unfortunately, up to now, vaccinationDetailed.tsv was corrupted during the aggregation of seeds. The column "number" contained values like 1.4 or 2.6 instead of integers. The problem has been fixed starting with the 0.zip in https://svn.vsp.tu-berlin.de/repos/public-svn/matsim/scenarios/countries/de/episim/battery/jakob/2022-11-04/1-snap/summaries/

Thus, in terms of back-compatibility, these should be three cases:
1) vaccinationDetailed.tsv doesn't exist: use old way of making plot using  infections.txt.csv
2) vaccinationDetailed.tsv  exists but is corrupted : use old way of making plot using  infections.txt.csv
3) vaccinationDetailed.tsv  exists  and is not corrupted (contains only integers in column "number"): use vaccinationDetailed.tsv

If #2 is too complicated to implement in covid-sim, we could maybe also just delete all corrupted vaccinationDetailed.tsv  files, so as to turn all #2 cases into #1 cases.

**Comment by frievoe97** [comment]
/public-svn/matsim/scenarios/countries/de/episim/battery/jakob/2022-10-09/2-meas
/public-svn/matsim/scenarios/countries/de/episim/battery/jakob/2022-11-16/1-bq
