### ISSUE TITLE
"Cologne Cases Comparison": show every seed as one trajectory

### ISSUE THREAD

**Issue by jakobrehmann** [matsim-vsp/covid-sim#41]
We are interested in turning the above-mentioned plot into more of an ensemble forecast (see end of website page for example https://covid19scenariohub.eu/report2.html ). This means we want to show the trajectory of every seed behind the aggregated (blue) line. As discussed with @frievoe97, those seed-lines could be turned on and off with a button.

I would propose the following steps:

@rakow - The planned course of action is for the aggregation script to add "nShowSymptomsCum" columns to infections.txt.csv for each seed. e.g. "nShowSymptomsCum_seed_4711". A keyword like "seed" would be important in the column name so that the relevant columns can automatically be selected without hard-coding. 

@jakobrehmann - start a run and provide an updated infections.txt.csv to @frievoe97 

@frievoe97 - update "Cologne Cases Comparison"

**Comment by rakow** [comment]
The required file is now generated when aggregating: infectionsPerSeed.tsv

**Comment by jakobrehmann** [comment]
Thanks @rakow . The new output file can be found in the following run:
/jakob/2022-11-18/3-mandates-seeds/
